version: "3.10"

services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: sqlite+aiosqlite:////data/app.db
      JWT_SECRET_KEY: super-secret-change-me
      JWT_ALGORITHM: HS256
      JWT_EXPIRATION_MINUTES: 1440
      RATE_LIMIT_REQUESTS: 600
      RATE_LIMIT_WINDOW_SECONDS: 60
    volumes:
      - sqlite_data:/data

volumes:
  sqlite_data:
