#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env"
VENV_PATH="$PROJECT_ROOT/.venv"
REQUIREMENTS_FILE="$PROJECT_ROOT/requirements.txt"

log() {
  echo "[setup] $1"
}

if [ -f "$ENV_FILE" ]; then
  log ".env already exists, leaving it untouched"
else
  log "Generating development .env file"
  cat <<'ENVEOF' > "$ENV_FILE"
# Generated by scripts/setup_codespace.sh
DATABASE_URL=sqlite+aiosqlite:///./app.db
JWT_SECRET_KEY=dev-super-secret-key
JWT_ALGORITHM=HS256
JWT_EXPIRATION_MINUTES=1440
RATE_LIMIT_REQUESTS=120
RATE_LIMIT_WINDOW_SECONDS=60
INITIAL_ADMIN_EMAIL=admin@example.com
INITIAL_ADMIN_PASSWORD=change-me-now
CORS_ALLOW_ORIGINS=["*"]
ENVEOF
fi

if [ -f "$VENV_PATH/bin/activate" ]; then
  log "Virtualenv already exists at $VENV_PATH"
else
  PYTHON_BIN=${PYTHON_BIN:-python3}
  log "Creating virtualenv using $PYTHON_BIN"
  "$PYTHON_BIN" -m venv "$VENV_PATH"
fi

# shellcheck disable=SC1090
source "$VENV_PATH/bin/activate"

log "Upgrading pip"
pip install --upgrade pip >/dev/null

log "Installing dependencies from $REQUIREMENTS_FILE"
pip install -r "$REQUIREMENTS_FILE"

log "Setup completed. Activate the environment with: source $VENV_PATH/bin/activate"
